### ISSUE TITLE
DCP

### ISSUE THREAD

**Issue by savent404** [savent404/spn#1]
Fully supported PN-DCP protocol when acting IOC/IOD

- [x] Query/Update records from SPN::DB
- [ ] Should get notified if IP suit changed by Upper
- [x] Multi-interface designed.
- [x] Add timeout mechanism 
  - [x] Ident response delay
  - [x] General UC client timeout
  - [ ] Quick startup
- [x] Ident
  - [x] All selector
  - [x] Filter
- [x] Set
  - [x] IP
  - [x] DEV PROP
    - [x] Should check name of station if lower case
  - [ ] DHCP
  - [ ] CONTROL
  - [ ] NME
- [x] Get
  - [x] IP
  - [x] DEV PROP
  - [ ] DHCP
  - [x] CONTROL
  - [ ] NME
- [ ] Hello

# State

### Multicast Receiver [multiple]

```mermaid
stateDiagram-v2
    [*] --> OPEN
    OPEN-->WRESP_MC: Idnetify.ind()
    note right of WRESP_MC
        Only if filter machedes
    end note
    WRESP_MC-->WTIME_MC: if respDelayFactor > 1
    WRESP_MC-->OPEN: Identify.rsp()
    WTIME_MC-->OPEN: Identify.rsp()
```
### Hello multicast  sender [singleton]
```mermaid
stateDiagram-v2
    [*] --> OPEN
    OPEN-->WACK_MC: Hello.req()
    WACK_MC-->OPEN : Hello.cof(+/-)
```

### Unicast receiver [singleton]
```mermaid
stateDiagram-v2
    [*] --> OPEN
    OPEN-->OPEN: Get.ind()<br/>Set.ind()<br/>
```
### Multicast sender [singleton]

Sender will wait for timer expired or link layer report errors
```mermaid
stateDiagram-v2
    [*] --> OPEN
    OPEN-->WACK_MC: Ident.req()
    WACK_MC-->TIMEOUT: TimerExpired()
    WACK_MC-->OPEN: Ident.cnf(-)<br/>StopTimer
    TIMEOUT-->OPEN: Ident.cnf(+)
```

### Hello multicast receiver [singleton]

```mermaid
stateDiagram-v2
    [*] --> OPEN
    OPEN-->OPEN: Hello.req()
```

### Unicast sender [singleton/multiple]

Sender will return to `OPEN` if Receiver responded or timer expired.

Considering the cost of multiple instance, we should limit the maximum instance on embedded controller

```mermaid
stateDiagram-v2
    [*] --> OPEN
    OPEN-->WACK_UC: Get.req()<br/>Set.req()<br/>Ident.req()
    WACK_UC-->TIMEOUT: RespTimerExpired()
    TIMEOUT-->OPEN: Get.cnf(-)<br/>Set.cnf(-)/Ident.cnf(-)
    WACK_UC-->OPEN: Get.cnf(+/-)<br/>Set.cnf(+/-)<br/>Ident.cnf(+)
```

# Capture list
- [dcp_ident_get.zip](https://github.com/user-attachments/files/16308525/dcp_ident_get.zip)
- [dcp_ident_get.zip](https://github.com/user-attachments/files/16484466/dcp_ident_get.zip)
