### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by savent404** [savent404/spn#2]
- [ ] Multi-interface designed.
- [ ] Provide adapted API with async method.
  - [ ] Consider task priority and the cost of context switch in ASYN mode.
- [ ] Provide adapted API with sync method.
  - [ ] Consider critical section when callback called in SYNC mode.
- [ ] #3
  - [ ] Limited fixed built-in parameters for performance optimizing.
